[project]
name = "autoferam"
version = "0.1.0"
description = "Automate Feram simulations."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansicolors>=1.1.8",
    "numpy>=2.2.1",
    "pandas>=2.2.3",
    "polars>=1.18.0",
    "result>=0.17.0",
]
